export const COMMAND_TOKEN = 'COMMAND';
export const QUERY_TOKEN = 'QUERY';

export const SERVICE_TOKENS = {
  ATTENDANCE_TOKEN: 'ATTENDANCE',
  JUDGING_TOKEN: 'JUDGING',
  LATTICE_TOKEN: 'LATTICE',
  REGISTRATION_TOKEN: 'REGISTRATION',
};
