export const COMMAND_TOKEN = 'COMMAND';
export const QUERY_TOKEN = 'QUERY';

export const SERVICE_TOKENS = {
  ATTENDANCE: 'ATTENDANCE',
  JUDGING: 'JUDGING',
  LATTICE: 'LATTICE',
  REGISTRATION: 'REGISTRATION',
};
