export const ENV = {
  DATABASE_URL: `DATABASE_URL`,
  production: `production`,
  PORT: `PORT`,
  CRYPTO_KEY: `CRYPTO_KEY`,
  SENDGRID_API_KEY: `SENDGRID_API_KEY`,
  JUDGE_PASSWORD: `JUDGE_PASSWORD`,
  DEVPOST_TITLE_COLUMN: `DEVPOST_TITLE_COLUMN`,
  DEVPOST_URL_COLUMN: `DEVPOST_URL_COLUMN`,
  DEVPOST_CATEGORY_COLUMN: `DEVPOST_CATEGORY_COLUMN`,
  DEVPOST_TABLE_NUMBER_COLUMN: `DEVPOST_TABLE_NUMBER_COLUMN`,
};
